export const FETCH_ACCOUNT_START = "FETCH_ACCOUNT_START";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILED = "FETCH_ACCOUNT_FAILED";
export const FETCH_ACCOUNT_STOP = "FETCH_ACCOUNT_STOP";